# Etapa 1: Construcción de la aplicación
FROM node:22.2.0-alpine AS build

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente
COPY . .

# Compila la aplicación
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:1.18.0-alpine

# Copia los archivos de la build de React en el directorio HTML de Nginx
COPY --from=build /app/out /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
