apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-react-next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-react-next
  template:
    metadata:
      labels:
        app: app-react-next
    spec:
      containers:
      - name: app-react-next
        image: docker.io/devojeda/app-react-next:0.1
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
