name: CI

on:
  push:
    branches: [ "feature/init" ]
  pull_request:
    branches: [ "feature/init" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cache de dependencias de npm
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --legacy-peer-deps --loglevel=warn

      # Cache de la build de Next.js
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-

      - name: Run ESLint
        run: npm run lint

      - name: Build Next.js app
        run: npm run build
